services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oshpoint-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: ${TZ:-Asia/Bishkek}
      ALEMBIC_AUTOUPGRADE: ${ALEMBIC_AUTOUPGRADE:-1}
      # подстраховка по именам каналов
      BIKE_CHANNEL: ${BIKE_CHANNEL:-${BOT_BIKE_CHANNEL:-}}
      BIKE_TOPIC_ID: ${BIKE_TOPIC_ID:-${BOT_BIKE_TOPIC_ID:-}}
    volumes:
      - ./data:/app/data
